(function (win, ysp) {
  ysp.runtime.Model.extendLoadingModel({
    getData_control1_mqtMl7: function (elem) {},
    doAction_uiControl1_rkoQ7K: function (data, elem) {
      if (data.eventType == 'handleBackBtnClick') {
        ysp.appMain.closeWindow();
      }
    },
    getTemplate_uiControl1_rkoQ7K: function () {
      var selfTemplate = 'export default class PageHeader extends React.Component{\n  constructor (props){\n    super(props);\n    \n  }\n  handleBackBtnClick () {\n    this.props.customHandler({\n      eventType: \'handleBackBtnClick\'\n    })\n  }\n  render () {\n    return <h4 className=\'pageHeader\'>\n      <span className=\'backBtn\' onClick={() => this.handleBackBtnClick() }>\u8FD4\u56DE</span>\n    </h4>\n  }\n}';
      return '\'use strict\';\n\nObject.defineProperty(exports, "__esModule", {\n  value: true\n});\n\nvar _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();\n\nfunction _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }\n\nfunction _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn\'t been initialised - super() hasn\'t been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }\n\nfunction _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }\n\nvar PageHeader = function (_React$Component) {\n  _inherits(PageHeader, _React$Component);\n\n  function PageHeader(props) {\n    _classCallCheck(this, PageHeader);\n\n    return _possibleConstructorReturn(this, (PageHeader.__proto__ || Object.getPrototypeOf(PageHeader)).call(this, props));\n  }\n\n  _createClass(PageHeader, [{\n    key: \'handleBackBtnClick\',\n    value: function handleBackBtnClick() {\n      this.props.customHandler({\n        eventType: \'handleBackBtnClick\'\n      });\n    }\n  }, {\n    key: \'render\',\n    value: function render() {\n      var _this2 = this;\n\n      return React.createElement(\n        \'h4\',\n        { className: \'pageHeader\' },\n        React.createElement(\n          \'span\',\n          { className: \'backBtn\', onClick: function onClick() {\n              return _this2.handleBackBtnClick();\n            } },\n          \'\\u8FD4\\u56DE\'\n        )\n      );\n    }\n  }]);\n\n  return PageHeader;\n}(React.Component);\n\nexports.default = PageHeader;';
    },
    getData_control52_WKBZT3: function (elem) {
      if (elem) {
        if (elem.querySelector('#tree_nodes_0').children.length == 0) {
          var ypt = elem.ownerDocument.querySelector('#nav li[title="云平台测试专区"]');ypt && ypt.click();
        }var menuArr = [];var menus = ["存贷款、备付金存款日报表（银监口径）", "人民币储蓄存款余额", "人民币储蓄存款日均", "个人帐户存款区间大额变动查询", "储蓄单笔变动大额查询情况表", "对公帐户存款日大额变动查询", "对公存款余额增减情况日表", "开户清单查询打印"];$(elem).children('div').children('#tree_nodes_0').children('div').each(function (divIdx, div) {
          if (menus.indexOf(div.textContent) != -1) {
            menuArr.push(div.textContent);
          }
        });return { menuArr: menuArr };
      } else {
        return null;
      }
    },
    doAction_uiControl3_mpK0PL: function (data, elem) {
      if (data.eventType == 'handleMenuClick') {
        var dataCustom = data.dataCustom;$(elem).children('div').children('#tree_nodes_0').children('div').eq(dataCustom).children('span')[0].click();ysp.appMain.showLoading();
      }
    },
    getTemplate_uiControl3_mpK0PL: function () {
      var selfTemplate = 'export default class extends React.Component{\n  constructor(props){\n    super(props);\n  }\n  handleMenuClick(e){\n    var index = e.target.dataset.index;\n    this.props.customHandler({\n      data: index,\n      eventType: \'handleMenuClick\'\n    })\n  }\n  render(){\n    var data = this.props.customData;\n    if (data) {\n      return <div className=\'menuContainer\'>\n      \t<ul onClick={ (e) => this.handleMenuClick(e) }>\n        \t{\n            data.menuArr.map( (menu, menuIdx) => {\n              return <li data-index={menuIdx}>{menu}</li>\n            })\n          }\n        </ul>\n      </div>\n    } else {\n      return null;\n    }\n    \n  }\n}';
      return "'use strict';\n\nObject.defineProperty(exports, \"__esModule\", {\n  value: true\n});\n\nvar _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if (\"value\" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();\n\nfunction _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError(\"Cannot call a class as a function\"); } }\n\nfunction _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError(\"this hasn't been initialised - super() hasn't been called\"); } return call && (typeof call === \"object\" || typeof call === \"function\") ? call : self; }\n\nfunction _inherits(subClass, superClass) { if (typeof superClass !== \"function\" && superClass !== null) { throw new TypeError(\"Super expression must either be null or a function, not \" + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }\n\nvar _class = function (_React$Component) {\n  _inherits(_class, _React$Component);\n\n  function _class(props) {\n    _classCallCheck(this, _class);\n\n    return _possibleConstructorReturn(this, (_class.__proto__ || Object.getPrototypeOf(_class)).call(this, props));\n  }\n\n  _createClass(_class, [{\n    key: 'handleMenuClick',\n    value: function handleMenuClick(e) {\n      var index = e.target.dataset.index;\n      this.props.customHandler({\n        data: index,\n        eventType: 'handleMenuClick'\n      });\n    }\n  }, {\n    key: 'render',\n    value: function render() {\n      var _this2 = this;\n\n      var data = this.props.customData;\n      if (data) {\n        return React.createElement(\n          'div',\n          { className: 'menuContainer' },\n          React.createElement(\n            'ul',\n            { onClick: function onClick(e) {\n                return _this2.handleMenuClick(e);\n              } },\n            data.menuArr.map(function (menu, menuIdx) {\n              return React.createElement(\n                'li',\n                { 'data-index': menuIdx },\n                menu\n              );\n            })\n          )\n        );\n      } else {\n        return null;\n      }\n    }\n  }]);\n\n  return _class;\n}(React.Component);\n\nexports.default = _class;";
    }
  }, "baobiaozhuanqu");
})(window, ysp);