(function (win, ysp) {
  ysp.runtime.Model.extendLoadingModel({
    getData_control108_MGvaT7: function (elem) {
      if (!elem) {
        return;
      }return elem.querySelector(".mini-panel-title").textContent;
    },
    doAction_uiControl93_HFQSLT: function (data, elem) {
      if (data.eventType == "back") {
        elem.querySelector(".mini-tools-close").click();
      }
    },
    getTemplate_uiControl93_HFQSLT: function () {
      var selfTemplate = "import { Header, HeaderLeft, HeaderRight } from 'ysp-interior-components';\nmodule.exports = React.createClass({\n  back:function(){\n    var handler=this.props.customHandler;\n    if(handler){\n      handler({\n        eventType:\"back\"\n      })\n    }\n  },\n  render: function() {\n    var data = this.props.customData;\n    return (\n      <Header amStyle=\"primary\" title={data}>\n        <HeaderLeft>\n          <AMUI.Button amStyle=\"primary\" style={{ margin: 0 }} onClick={this.back}><span className=\"icon icon-left-nav\"></span>\u8FD4\u56DE</AMUI.Button>\n        </HeaderLeft>\n        <HeaderRight>\n          \n        </HeaderRight>\n      </Header>\n    );\n  }\n});";
      return "\"use strict\";\n\nvar _yspInteriorComponents = require(\"ysp-interior-components\");\n\nmodule.exports = React.createClass({\n  displayName: \"exports\",\n\n  back: function back() {\n    var handler = this.props.customHandler;\n    if (handler) {\n      handler({\n        eventType: \"back\"\n      });\n    }\n  },\n  render: function render() {\n    var data = this.props.customData;\n    return React.createElement(\n      _yspInteriorComponents.Header,\n      { amStyle: \"primary\", title: data },\n      React.createElement(\n        _yspInteriorComponents.HeaderLeft,\n        null,\n        React.createElement(\n          AMUI.Button,\n          { amStyle: \"primary\", style: { margin: 0 }, onClick: this.back },\n          React.createElement(\"span\", { className: \"icon icon-left-nav\" }),\n          \"\\u8FD4\\u56DE\"\n        )\n      ),\n      React.createElement(_yspInteriorComponents.HeaderRight, null)\n    );\n  }\n});";
    },
    getData_control109_hPuU0s: function (elem) {
      if (!elem) {
        return;
      }var iframe = $(elem).parent().next()[0].querySelector("iframe") && $(elem).parent().next()[0].querySelector("iframe").contentWindow;if (!iframe) {
        return;
      }var _elem = iframe.document.querySelector(".mini-toolbar").querySelector("td");var buttons = _elem && _elem.children;var data = [];for (var i = 0; i < buttons.length; i++) {
        if ($(buttons[i]).hasClass("separator")) {
          break;
        }if (buttons[i].style.display == "none") {
          continue;
        }if ($(buttons[i]).hasClass("mini-button-disabled")) {
          continue;
        }var obj = { title: buttons[i].textContent.trim(), index: i };if (obj.title == "搜索") {
          continue;
        }if (obj.title == "删除") {
          obj.hollow = true;obj.amStyle = "alert";
        }data.push(obj);
      }return data;
    },
    doAction_uiControl94_Zewh0V: function (data, elem) {
      var iframe = $(elem).parent().next()[0].querySelector("iframe").contentWindow;if (!iframe) {
        return;
      }var _elem = iframe.document.querySelector(".mini-toolbar").querySelector("td");var buttons = _elem && _elem.children;if (data.eventType == "clickButton") {
        buttons[data.customData].click();
      }
    },
    getTemplate_uiControl94_Zewh0V: function () {
      var selfTemplate = "const Container = AMUI2.Container;\nconst ButtonAction = AMUI2.ButtonAction;\nconst wrapStyle = {\n  margin: '8px 4px',\n  padding: 0,\n  background: '#fff',\n  borderRadius: '4px'\n};\n\nconst ListStyle = {\n  listStyle: 'none',\n  color: '#3d8cf8',\n  padding: 0,\n  marginLeft: '15px',\n  marginRight: '15px'\n};\n\nconst listStyle = {\n  borderBottom: '1px solid #d8d8d8',\n  paddingTop: '14px',\n  paddingBottom: '14px',\n  lineHeight: 1,\n};\n\nconst listLastStyle = {\n  paddingTop: '14px',\n  paddingBottom: '14px',\n  lineHeight: 1,\n};\nmodule.exports = React.createClass({\n  clickButton:function(e){\n    var obj = this.props.customData;\n    var current = e.target.innerHTML;\n    function index(current, obj){ \n      for (var i = 0, length = obj.length; i<length; i++) { \n        if (obj[i].title == current) {\n        \treturn obj[i].index; \n        } \n      } \n    }\n    var index = index(current,obj);\n    var handler = this.props.customHandler;\n    if(handler){\n      handler({\n        eventType:\"clickButton\",\n        data:index\n      })\n    }\n  },\n  clickOthers:function(e){\n    var handler = this.props.customHandler;\n    var index = e.target.attributes[\"data-index\"].value;\n    if(handler){\n      handler({\n        eventType:\"clickButton\",\n        data:index\n      })\n    }\n  },\n  render: function() {\n    var data = this.props.customData;\n    if(!data||data.length==0){\n      return(<div></div>);\n    }\n    var obj = this.props.customData;\n    var actions = [];\n    var others = [];\n    for (var i = 0, length = obj.length; i<length; i++) {\n      if(length<3){\n        actions.push(obj[i]);\n      }else{\n        if(i==0||obj[i].title==\"\u5220\u9664\"){\n          actions.push(obj[i])\n        }else{\n          others.push(obj[i])\n        }\n      }\n    }\n    if(actions.length<2&&others.length>0){\n      actions.push(others.shift())\n    }\n    actions[0].onClick=this.clickButton;\n    actions[1]?actions[1].onClick=this.clickButton:\"\";\n    var me = this;\n    return (\n      <Container>\n        <ButtonAction\n          actions={actions}\n        >\n          {data.length>2?\n            <div style={wrapStyle}>\n              <ul style={ListStyle}>\n                {others.map(function(item,i){\n                  return(\n                    <li onClick={me.clickOthers} data-index={item.index} style={i==others.length-1?listLastStyle:listStyle}>{item.title}</li>\n                  )\n                })}\n              </ul>\n            </div>:\n          \tundefined\n          }\n          \n        </ButtonAction>\n      </Container>\n    )\n  }\n});";
      return "'use strict';\n\nvar Container = AMUI2.Container;\nvar ButtonAction = AMUI2.ButtonAction;\nvar wrapStyle = {\n  margin: '8px 4px',\n  padding: 0,\n  background: '#fff',\n  borderRadius: '4px'\n};\n\nvar ListStyle = {\n  listStyle: 'none',\n  color: '#3d8cf8',\n  padding: 0,\n  marginLeft: '15px',\n  marginRight: '15px'\n};\n\nvar listStyle = {\n  borderBottom: '1px solid #d8d8d8',\n  paddingTop: '14px',\n  paddingBottom: '14px',\n  lineHeight: 1\n};\n\nvar listLastStyle = {\n  paddingTop: '14px',\n  paddingBottom: '14px',\n  lineHeight: 1\n};\nmodule.exports = React.createClass({\n  displayName: 'exports',\n\n  clickButton: function clickButton(e) {\n    var obj = this.props.customData;\n    var current = e.target.innerHTML;\n    function index(current, obj) {\n      for (var i = 0, length = obj.length; i < length; i++) {\n        if (obj[i].title == current) {\n          return obj[i].index;\n        }\n      }\n    }\n    var index = index(current, obj);\n    var handler = this.props.customHandler;\n    if (handler) {\n      handler({\n        eventType: \"clickButton\",\n        data: index\n      });\n    }\n  },\n  clickOthers: function clickOthers(e) {\n    var handler = this.props.customHandler;\n    var index = e.target.attributes[\"data-index\"].value;\n    if (handler) {\n      handler({\n        eventType: \"clickButton\",\n        data: index\n      });\n    }\n  },\n  render: function render() {\n    var data = this.props.customData;\n    if (!data || data.length == 0) {\n      return React.createElement('div', null);\n    }\n    var obj = this.props.customData;\n    var actions = [];\n    var others = [];\n    for (var i = 0, length = obj.length; i < length; i++) {\n      if (length < 3) {\n        actions.push(obj[i]);\n      } else {\n        if (i == 0 || obj[i].title == \"\u5220\u9664\") {\n          actions.push(obj[i]);\n        } else {\n          others.push(obj[i]);\n        }\n      }\n    }\n    if (actions.length < 2 && others.length > 0) {\n      actions.push(others.shift());\n    }\n    actions[0].onClick = this.clickButton;\n    actions[1] ? actions[1].onClick = this.clickButton : \"\";\n    var me = this;\n    return React.createElement(\n      Container,\n      null,\n      React.createElement(\n        ButtonAction,\n        {\n          actions: actions\n        },\n        data.length > 2 ? React.createElement(\n          'div',\n          { style: wrapStyle },\n          React.createElement(\n            'ul',\n            { style: ListStyle },\n            others.map(function (item, i) {\n              return React.createElement(\n                'li',\n                { onClick: me.clickOthers, 'data-index': item.index, style: i == others.length - 1 ? listLastStyle : listStyle },\n                item.title\n              );\n            })\n          )\n        ) : undefined\n      )\n    );\n  }\n});";
    },
    getData_control120_OXhK3i: function (elem) {
      if (!elem) {
        return;
      }var tds = elem.querySelector(".mini-radiobuttonlist-table").querySelector("tbody").querySelector("tr").children;var checked1 = $(tds[0].children[0]).hasClass("mini-radiobuttonlist-item-selected");var checked2 = $(tds[1].children[0]).hasClass("mini-radiobuttonlist-item-selected");return [checked1, checked2];
    },
    doAction_uiControl108_5ix25R: function (data, elem) {
      var tds = elem.querySelector(".mini-radiobuttonlist-table").querySelector("tbody").querySelector("tr").children;if (data.eventType == "click") {
        var target = tds[data.customData].querySelector("label");target.click();
      }
    },
    getTemplate_uiControl108_5ix25R: function () {
      var selfTemplate = "module.exports = React.createClass({\n  click:function(e){\n    var handler = this.props.customHandler;\n    var index = e.target.attributes[\"data-index\"].value;\n    if(handler){\n      handler({\n        eventType:\"click\",\n        data:index\n      })\n    }\n  },\n  render: function() {\n    var data = this.props.customData;\n    if(!data){return(<div></div>)}\n    return (\n      <div style={{whiteSpace:\"nowrap\"}}>\n        <a style={{display:\"inline-block\",borderRadius:\"3px\"}} data-index={0} onClick={this.click} className={data[0]?\"btn btn-sm btn-primary\":\"btn btn-sm\"}>\u540C\u610F</a>\n        <a style={{display:\"inline-block\",borderRadius:\"3px\"}} data-index={1} onClick={this.click} className={data[1]?\"btn btn-sm btn-primary\":\"btn btn-sm\"}>\u4E0D\u540C\u610F</a>\n      </div>\n    )\n  }\n});";
      return "\"use strict\";\n\nmodule.exports = React.createClass({\n  displayName: \"exports\",\n\n  click: function click(e) {\n    var handler = this.props.customHandler;\n    var index = e.target.attributes[\"data-index\"].value;\n    if (handler) {\n      handler({\n        eventType: \"click\",\n        data: index\n      });\n    }\n  },\n  render: function render() {\n    var data = this.props.customData;\n    if (!data) {\n      return React.createElement(\"div\", null);\n    }\n    return React.createElement(\n      \"div\",\n      { style: { whiteSpace: \"nowrap\" } },\n      React.createElement(\n        \"a\",\n        { style: { display: \"inline-block\", borderRadius: \"3px\" }, \"data-index\": 0, onClick: this.click, className: data[0] ? \"btn btn-sm btn-primary\" : \"btn btn-sm\" },\n        \"\\u540C\\u610F\"\n      ),\n      React.createElement(\n        \"a\",\n        { style: { display: \"inline-block\", borderRadius: \"3px\" }, \"data-index\": 1, onClick: this.click, className: data[1] ? \"btn btn-sm btn-primary\" : \"btn btn-sm\" },\n        \"\\u4E0D\\u540C\\u610F\"\n      )\n    );\n  }\n});";
    },
    getData_control122_QcOJw6: function (elem) {
      if (!elem) {
        return;
      }var files = elem.children;var data = [];for (var i = 0; i < files.length; i++) {
        var file = {};var linka = files[i].querySelectorAll("a")[0];if (linka.href == "javascript:void(0);") {
          var str = linka.attributes["onclick"].value;file.url = str.split("'")[1];
        } else {
          var str = linka.href;file.url = "/down/" + str.split("/down/")[1];
        }file.name = linka.textContent;file.type = file.name.split(".")[1].toLowerCase();file.hasDelect = files[i].querySelectorAll("a")[1] ? true : false;data.push(file);
      }return data;
    },
    doAction_uiControl109_5oLZa2: function (data, elem) {
      var _doc = elem.ownerDocument;var url = _doc.defaultView.location.origin;var files = elem.children;if (data.eventType == "viewFile") {
        ysp.appMain.openDocument({ "type": "document", "downloadType": "get", "downloadUrl": url + data.customData });
      }if (data.eventType == "delectFile") {
        files[data.customData.index].querySelectorAll("a")[1].click();
      }
    },
    getTemplate_uiControl109_5oLZa2: function () {
      var selfTemplate = "module.exports = React.createClass({\n  viewFile:function(e){\n    var url = e.target.attributes[\"data-url\"].value;\n    var handler=this.props.customHandler;\n    if(handler){\n      handler({\n        eventType:\"viewFile\",\n        data:url\n      })\n    }\n  },\n  delectFile:function(e){\n    var index = e.target.attributes[\"data-index\"].value;\n    var handler=this.props.customHandler;\n    if(handler){\n      handler({\n        eventType:\"delectFile\",\n        data:{\n          index:index\n        }\n      })\n    }\n  },\n  render: function() {\n    var data = this.props.customData;\n    var me = this;\n    if(!data){return(<div></div>)}\n    return (\n      <div>\n        {data.map(function(item,i){\n          return(\n            <div className=\"card dec-card\">\n              <div className=\"card-body\">\n                <ul className=\"list\" style={{margin:0}}>\n                  <li className=\"item\">\n                    <div className=\"item-media\">\n                      <span className={\"icon icon-file icon-\"+item.type}></span>\n                    </div>\n                    <div data-url={item.url} onClick={me.viewFile} className=\"item-title\">{item.name}</div>\n                    <div className=\"item-after\" style={{display:item.hasDelect?\"\":\"none\"}}>\n                      <span style={{display:item.hasDelect?\"\":\"none\"}} data-index={i} onClick={me.delectFile} className=\"icon icon-close\"></span>\n                    </div>\n                  </li>\n                </ul>\n              </div>\n            </div>\n          )\n        })}\n      </div>\n    )\n  }\n});";
      return "\"use strict\";\n\nmodule.exports = React.createClass({\n  displayName: \"exports\",\n\n  viewFile: function viewFile(e) {\n    var url = e.target.attributes[\"data-url\"].value;\n    var handler = this.props.customHandler;\n    if (handler) {\n      handler({\n        eventType: \"viewFile\",\n        data: url\n      });\n    }\n  },\n  delectFile: function delectFile(e) {\n    var index = e.target.attributes[\"data-index\"].value;\n    var handler = this.props.customHandler;\n    if (handler) {\n      handler({\n        eventType: \"delectFile\",\n        data: {\n          index: index\n        }\n      });\n    }\n  },\n  render: function render() {\n    var data = this.props.customData;\n    var me = this;\n    if (!data) {\n      return React.createElement(\"div\", null);\n    }\n    return React.createElement(\n      \"div\",\n      null,\n      data.map(function (item, i) {\n        return React.createElement(\n          \"div\",\n          { className: \"card dec-card\" },\n          React.createElement(\n            \"div\",\n            { className: \"card-body\" },\n            React.createElement(\n              \"ul\",\n              { className: \"list\", style: { margin: 0 } },\n              React.createElement(\n                \"li\",\n                { className: \"item\" },\n                React.createElement(\n                  \"div\",\n                  { className: \"item-media\" },\n                  React.createElement(\"span\", { className: \"icon icon-file icon-\" + item.type })\n                ),\n                React.createElement(\n                  \"div\",\n                  { \"data-url\": item.url, onClick: me.viewFile, className: \"item-title\" },\n                  item.name\n                ),\n                React.createElement(\n                  \"div\",\n                  { className: \"item-after\", style: { display: item.hasDelect ? \"\" : \"none\" } },\n                  React.createElement(\"span\", { style: { display: item.hasDelect ? \"\" : \"none\" }, \"data-index\": i, onClick: me.delectFile, className: \"icon icon-close\" })\n                )\n              )\n            )\n          )\n        );\n      })\n    );\n  }\n});";
    }
  });
})(window, ysp);